# Generated by Django 6.1 on 2026-08-14 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendoruser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vendor User', 'verbose_name_plural': 'Vendor Users'},
        ),
        migrations.AddIndex(
            model_name='vendoruser',
            index=models.Index(fields=['vendor', 'is_active'], name='superadmin__vendor__137c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendoruser',
            index=models.Index(fields=['user', 'is_active'], name='superadmin__user_id_c0f742_idx'),
        ),
        migrations.AddIndex(
            model_name='vendoruser',
            index=models.Index(fields=['vendor', 'role'], name='superadmin__vendor__eb610c_idx'),
        ),
    ]
