# Generated by Django 6.1 on 2026-08-11 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='time_ago',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='api.patient'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='api.patient'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=30),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='patients_trend',
            field=models.CharField(default='0%', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='stock',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('due', 'Due')], db_index=True, default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_visit',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='reportmetric',
            name='generated_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reportmetric',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Completed', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('leave', 'On Leave'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
    ]
