# Generated by Django 6.1 on 2026-08-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_accessrole_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rolepermission',
            name='unique_role_permission',
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='role_permission'),
        ),
    ]
